export const QUERY_V2V_OSP_TENANT_ATTRIBUTES = 'QUERY_V2V_OSP_TENANT_ATTRIBUTES';
export const SET_V2V_INSTANCE_PROPERTIES_SINGLE_ROW = 'SET_V2V_INSTANCE_PROPERTIES_SINGLE_ROW';
export const SET_V2V_INSTANCE_PROPERTIES_ROWS = 'SET_V2V_INSTANCE_PROPERTIES_ROWS';
export const QUERY_V2V_OSP_BEST_FIT_FLAVOR = 'QUERY_V2V_OSP_BEST_FIT_FLAVOR';
export const SET_V2V_BEST_FIT_FLAVORS_IN_VM_ROWS = 'SET_V2V_BEST_FIT_FLAVORS_IN_VM_ROWS';