export const QUERY_V2V_OSP_TENANT_ATTRIBUTES = 'QUERY_V2V_OSP_TENANT_ATTRIBUTES';
export const QUERY_V2V_OSP_BEST_FIT_FLAVOR = 'QUERY_V2V_OSP_BEST_FIT_FLAVOR';
export const SAVE_PREVIOUS_ROW_FOR_UNDO = 'SAVE_PREVIOUS_ROW_FOR_UNDO';
export const SET_SECURITY_GROUPS_FOR_VMS = 'SET_SECURITY_GROUPS_FOR_VMS';
